[site]
title = "Lanxin Jiang"
description = "Assistant Professor of Accounting at Stony Brook University."
favicon = "/favicon.svg"
last_updated = "March 31, 2026"

[author]
name = "Lanxin Jiang"
title = "Assistant Professor"
institution = "Stony Brook University"
avatar = "/bio.jpg"

[social]
# Contact information (leave blank or delete to hide)

email = "lanxin.jiang@stonybrook.edu"
google_scholar = "https://scholar.google.com/citations?hl=en&user=04wH10cAAAAJ&view_op=list_works&gmla=AEk_c1sMzmdG6iS6LUPtGLp_wCj4_L61ukOlM-FvAEY5PJnkJURJSB4j2nrblMTf1zl3n7Dxew_F31jvJqQlX9fC"
linkedin = "https://www.linkedin.com/in/lanxin-jiang/"

[features]
# Show a like button on the about page
enable_likes = false

# Display all subpages on a single page
enable_one_page_mode = false

[i18n]
enabled = false
locales = ["zh", "en"]
default_locale = "en"
mode = "auto"
fixed_locale = "en"
persist = true
switcher = true

[i18n.labels]
zh = "中文"
en = "English"

[[navigation]]
title = "About"
type = "page"
target = "about"
href = "/"

[[navigation]]
title = "Publications"
type = "page"
target = "publications"
href = "/publications"

[[navigation]]
title = "Teaching"
type = "page"
target = "teaching"
href = "/teaching"

