[[news]]
date = "2026-02"
content = "Our work was published in Accounting Horizons."

[[news]]
date = "2026-01"
content = "Our work was featured by the Columbia Law School Blue Sky."

[[news]]
date = "2025-11"
content = "Our work was published in The Accounting Review."
