[[news]]
date = "2026-02"
content = "Our work was published in [Accounting Horizons](https://doi.org/10.2308/HORIZONS-2023-099)."

[[news]]
date = "2026-01"
content = "Our work was featured by the [Columbia Law School Blue Sky](https://clsbluesky.law.columbia.edu/2026/01/15/combating-corporate-greenwashing-with-blockchain-technology/)."

[[news]]
date = "2025-11"
content = "Our work was published in [The Accounting Review](https://doi.org/10.2308/TAR-2024-0035)."
