type = "card"
title = "Teaching"

[[items]]
title = "ACC 320 AI in Accounting and Assurance"
date = "2026 Spring"
content = " The overall course objective is to familiarize students with the concepts of AI and the way in which AI adds value to business, accounting, and auditing. In this context, AI refers to the technologies employed in enterprise accounting in the broadest sense, including Machine Learning (ML) and Natural Language Processing (NLP). This course introduces the concepts and applications of AI in modern organizations from the perspective of accounting and auditing. To illustrate the underlying logic and realization of AI in accounting and auditing, this course also introduces AI tools and demonstrates how to use them to analyze real-world data. Students will gain hands-on experience with AI software for accounting and auditing."
tags = ["Undergraduate", "Business"]



[[items]]
title = "ACC 214 Managerial Cost Anlysis and Applications"
date = "2025 Fall, 2026 Fall"
content = "A study of cost concepts, and theories and the implementation and evaluation of an accounting system as a source of information for decision making, planning, control, and evaluation of the organization by management. Other topics includes cost-volume-profit analysis, budgeting and variance analysis. The overall course objective is to familiarize students with cost accounting concepts and how to make business decisions using accounting information, while incorporating Excel modeling and data visualization to enhance students' analytical and decision-support skills. The course is designed for both accounting and non-accounting business majors."
tags = ["Undergraduate", "Business"]



[[items]]
title = "22:010:684 Intro to A.I."
date = "2022 Spring, 2023 Spring"
content = "AI is a technology that mimics human intelligence. In the era of big data and digitization, accounting professionals are supposed to have a better understanding of AI technologies in business and their work. The overall course objective is to familiarize students with the concepts of AI and the way in which AI adds value to business, accounting, and auditing. In this context, AI refers to the technologies employed in enterprise accounting in the broadest sense, including Machine Learning (ML), Natural Language Processing (NLP), and Robotic Process Automation (RPA). This course introduces the concepts and applications of AI in modern organizations from the perspective of accounting and auditing. To illustrate the underlying logic and realization of AI in accounting and auditing, this course also provides an introduction to AI tools and demonstrations of how to use them to analyze real-world data. Students will gain hands-on experience with AI software for accounting and auditing."
tags = ["Graduate", "Accounting"]
